# Generated by Django 2.1.1 on 2018-10-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20181003_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
